### ISSUE TITLE
[FEATURE] add a if/endif syntax in templates

### ISSUE THREAD

**Issue by philippe-levan** [Probesys/lotemplate#4]
### Is your feature request related to a problem? Please describe.

In my templates, I need to display one paragraph or one other according to a value sent by JSON.

The content of these paragraph should stay in the template (and not sent in the JSON).

For example in a status of a company I need a different paragraph if the company is an commercial company or a fundation.

### Describe the solution you'd like

I believe we could add a syntax like this in the .odt files :+1: 

```
[if $status="SARL"]
This company needs at least 2 or 3 people...
[endif]

[if $status="SA"]
This company needs at least 9 people...
[endif]
```

then if $status="SARL" then we display the first paragraph and removes the second one.

### Describe alternatives you've considered

At the beginning I imagine to send the paragraph values in the JSON, but the text inside the [if xx] [endif] can be long and can contain some formatting. Furthermore, the people that will do the templates will be non technical people. It is easier for them to have these paragraphs inside the odt files.

**Comment by Kyrela** [comment]
While implementing this feature is possible, it won't be without problems. I tried writing a basic, standalone version using regexes:

```py
import regex

condition_bloc_pattern = regex.compile(
    # match patterns like [ si condition ] or <if condition> (exemples)
    r'(?:[\[<{(] *(?:if|si) +(?<condition>[^\n]+?) *[)}>\]]\s*)'
    # match any text
    r'(?<result>.*?)'
    # match patterns like [ finsi ] or <endif> (exemples)
    r'(?:\s*[\[<{(] *(?:endif|finsi) *[)}>\]])'
    # match backslash (if any)
    r'(?<bs>\n?)',
    regex.I | regex.M | regex.S
)

variable_pattern = regex.compile(
    r'\$(?<var>\w+)',
    regex.I | regex.M | regex.S
)

variables = {
    'status': 'SARL',
    'nom': 'Dupont',
    'prenom': 'Jean',
}

text = """
Placeholder text
[if $status == "SARL"]
YES SARL
[endif]
Placeholder text
[if $status == "RL"]
YES RL
[endif]
Placeholder text
"""

for match in condition_bloc_pattern.finditer(text):
    match: regex.Match
    cond = match['condition']
    cond = variable_pattern.sub(r"variables['\g<var>']", cond)

    # if cond, replace the matched bloc by the result in the text,
    # else remove it
    if eval(cond):
        text = text.replace(match[0], match['result'] + match['bs'])
    else:
        text = text.replace(match[0], '')

print(text)
```

And it works pretty well, as it returns
```

Placeholder text
YES SARL
Placeholder text
Placeholder text

```

But when I tried to implement it in lotemplate (patch below), I ran at a few issues


```diff
Subject: [PATCH] if/endif syntax POC
---
Index: lotemplate/classes.py
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/lotemplate/classes.py b/lotemplate/classes.py
--- a/lotemplate/classes.py	(revision 6f0895954c05ccf68b8d2d2455d03116a140b2af)
+++ b/lotemplate/classes.py	(date 1674230299430)
@@ -436,6 +436,38 @@
                 dict_of(self.cnx.host, self.cnx.port)
             ) from e
 
+        import regex
+        condition_bloc_pattern = regex.compile(
+            # match patterns like [ si condition ] or <if condition> (exemples)
+            r'(?:[\[<{(] *(?:if|si) +(?<condition>[^\n]+?) *[)}>\]]\s*)'
+            # match any text
+            r'(?<result>.*?)'
+            # match patterns like [ finsi ] or <endif> (exemples)
+            r'(?:\s*[\[<{(] *(?:endif|finsi) *[)}>\]])'
+            # match backslash (if any)
+            r'(?<bs>\n?)',
+            regex.I | regex.M | regex.S
+        )
+        variable_pattern = regex.compile(
+            r'\$(?<var>\w+)',
+            regex.I | regex.M | regex.S
+        )
+        raw_string = self.new.getText().getString()
+
+        for match in condition_bloc_pattern.finditer(raw_string):
+            match: regex.Match
+            cond = match['condition']
+            cond = variable_pattern.sub(r"variables['\g<var>']['value']", cond)
+            # cond = cond.replace('=', '==').replace('vrai', 'True')
+            # cond = cond.replace('faux', 'False')
+
+            # if cond, replace the matched bloc by the result in the text,
+            # else remove it
+            if eval(cond):
+                text_fill(self.new, match[0], match['result'])
+            else:
+                text_fill(self.new, match[0], "")
+
         for var, details in sorted(variables.items(), key=lambda s: -len(s[0])):
             if details['type'] == 'text':
                 text_fill(self.new, "$" + var, details['value'])
```

First, LibreOffice is unable to perform a multi-line (or at least multi-paragraph, whatever that means) search using `SearchDescriptor` (the search component used by the `text_fill` function), even with regex by setting its `SearchRegularExpression` attribute to `True`.[^1][^2]

[^1]: ["Search strings and line breaks with pyUNO" on StackOverflow](https://stackoverflow.com/questions/33912147/search-strings-and-line-breaks-with-pyuno)
[^2]: ["Using Regular Expressions in Text Searches" on LibreOffice Help](https://help.libreoffice.org/latest/lo/text/swriter/guide/search_regexp.html)

It means we'll have to search for a workaround, a new syntax for theses condition blocs or a new way to search them (and it also means that the code above doesn't work)

Second problem, using `XTextRange.String.replace()` (again, the replace method used by the `text_fill` function) doesn't preserve formatting of the text, but set it (for the whole replacement) to the same values as the first character of the replaced text (or, to be precise, to the values set before that character). In short, the text formatting will be gone when using this method.

We'll have to manually delete the `[if <cond>]` and `[endif]` lines in order to preserve it (because no replace will be done), which is possible but require some additionnal code.

---
For all these reasons and the fact that this addition is not a priority, it is not planned to add this functionality to lotemplate for the moment. Nevertheless, I invite you to open a pull request if you decide to implement this feature yourself in order to add it to lotemplate, in which case I would gladly accept it.

If you need some help or have question concerning the development of this feature, feel free to comment this issue, open a new [discussion](https://github.com/Probesys/lotemplate/discussions) or contact me directly.

**Comment by philippe-levan** [comment]
Hi,
I created a PR for this issue : https://github.com/Probesys/lotemplate/pull/5
Best regards,
Philippe

**Comment by cyrilus** [comment]
done

**Comment by cyrilus** [comment]
ok
